config/routes.rb
Rails.application.routes.draw do
  # scope format: false do
  #   defaults format: 'html' do
  resources :zones, param: :name, constraints: { name: /[^\/]+/ }, format: false, defaults: { format: 'html' } do
    resources :dns_records
  end
  #   end
  # end
  get 'home/index'
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  unauthenticated do
    root to: 'home#index', as: 'unauthenticated_root'
  end
  authenticated  do
      root to: 'zones#index'
   end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dns_record.rb
class DnsRecord < ApplicationRecord
  belongs_to :zone, touch: true

  enum record_type: [ :A, :AAAA, :CNAME, :NS, :PTR, :TXT ]
  validates :record_type, inclusion: { in: record_types.keys }

  def dump
    records = {
      "A" => DNS::Zone::RR::A.new,
      "AAAA" => DNS::Zone::RR::AAAA.new,
      "CNAME" => DNS::Zone::RR::CNAME.new,
      "NS" => DNS::Zone::RR::NS.new,
      "PTR" => DNS::Zone::RR::PTR.new,
      "TXT" => DNS::Zone::RR::TXT.new,
    }
    rec = records[record_type]
    rec.ttl = ttl
    rec.label = name
    rec.address = value
    rec
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include desired devise modules. Others available are:
  # :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable

  has_many :zones
end

app/models/zone.rb
class Zone < ApplicationRecord
  belongs_to :user
  has_many :dns_records, dependent: :destroy

  def dump
    zone = DNS::Zone.new
    zone.soa.serial = updated_at.strftime("%Y%m%d01")
    zone.origin = "#{self.name}."
    zone.ttl = '1d'

    # quick access to SOA RR
    zone.soa.nameserver = 'ns0.cloudlibre.example.com.'
    zone.soa.email = 'hostmaster.cloudlibre.example.com.'

    # add an A RR
    self.dns_records.each do |rec|
      zone.records << rec.dump unless rec.record_type.nil?
    end
    # output using dns zone file format
    zone.dump
  end

  def to_param
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!
end

app/controllers/dns_records_controller.rb
class DnsRecordsController < ApplicationController
  before_action :get_zone

  # POST /dns_records
  # POST /dns_records.json
  def create
    @dns_record = @zone.dns_records.build(dns_record_params)
    @dns_record.ttl = (30 * 60) if @dns_record.ttl.nil?
    respond_to do |format|
      if @dns_record.save
        format.html { redirect_to zone_path(@zone), notice: 'DNS Record was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        puts "failed to save DNS record: #{@dns_record.errors.to_json}"
        format.html { render 'zones/show' }
        format.json { render json: @dns_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dns_records/1
  # PATCH/PUT /dns_records/1.json
  def update
    @dns_record = @zone.dns_records.find_by(id: params[:id])
    respond_to do |format|
      if @dns_record.update(dns_record_params)
        format.html { redirect_to zone_path(@zone), notice: 'DNS Record was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @dns_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dns_records/1
  # DELETE /dns_records/1.json
  def destroy
    @dns_record = @zone.dns_records.find_by(id: params[:id])
    @dns_record.destroy
    respond_to do |format|
      format.html { redirect_to zone_path(@zone), notice: 'DNS Record was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def get_zone
   @zone = Zone.find_by(name: params[:zone_name])
  end

  def dns_record_params
    p = params.require(:dns_record).permit(:record_type, :name, :value, :ttl, :zone_id)
    p[:record_type] = DnsRecord.record_types[params[:dns_record][:record_type]]
    p
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!
  def index
  end
end

app/controllers/zones_controller.rb
class ZonesController < ApplicationController
  before_action :set_zone, only: [:show, :edit, :update, :destroy]

  # GET /zones
  # GET /zones.json
  def index
    @zones = current_user.zones
  end

  # GET /zones/1
  # GET /zones/1.json
  def show
    @dns_record = @zone.dns_records.build
  end

  # GET /zones/new
  def new
    @zone = Zone.new
  end

  # GET /zones/1/edit
  def edit
  end

  # POST /zones
  # POST /zones.json
  def create
    @zone = Zone.new(zone_params)
    @zone.user = current_user

    respond_to do |format|
      if @zone.save
        format.html { redirect_to @zone, notice: 'Zone was successfully created.' }
        format.json { render :show, status: :created, location: @zone }
      else
        format.html { render :new }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zones/1
  # PATCH/PUT /zones/1.json
  def update
    respond_to do |format|
      if @zone.update(zone_params)
        format.html { redirect_to @zone, notice: 'Zone was successfully updated.' }
        format.json { render :show, status: :ok, location: @zone }
      else
        format.html { render :edit }
        format.json { render json: @zone.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zones/1
  # DELETE /zones/1.json
  def destroy
    @zone.destroy
    respond_to do |format|
      format.html { redirect_to zones_url, notice: 'Zone was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_zone
      @zone = Zone.find_by(name: params[:name])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def zone_params
      params.require(:zone).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dns_record_helper.rb
module DnsRecordHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/zones_helper.rb
module ZonesHelper
end

app/views/home/index.html.erb
<h1>Home</h1>
<p>Ready to say something about how this is a DNS manager</p>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Edit account', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Sign in', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sign up', new_user_registration_path, class: 'nav-link' %></li>
<% end %>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">CloudLibre</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <%= render 'layouts/navigation_links' %>

    </ul>
    <ul class="navbar-nav mr-right">
      <%= render 'layouts/nav_links_for_auth' %>
    </ul>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Dashboard" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Dashboard" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <div class="container-fluid">
         <%= yield %>
       </div>
    </main>
  </body>
</html>

app/views/zones/_form.html.erb
<%= form_with(model: zone, local: true) do |form| %>
  <% if zone.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(zone.errors.count, "error") %> prohibited this zone from being saved:</h2>

      <ul>
        <% zone.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name, "Site name (example.com):" %>
    <%= form.text_field :name %>
  </div>

  <%= form.submit %>
<% end %>

app/views/zones/edit.html.erb
<h1>Editing Zone</h1>

<%= render 'form', zone: @zone %>

<%= link_to 'Show', @zone %> |
<%= link_to 'Back', zones_path %>

app/views/zones/index.html.erb
<!-- <p id="notice"><%= notice %></p>

<h1>Zones</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @zones.each do |zone| %>
      <tr>
        <td><%= zone.name %></td>
        <td><%= link_to 'Show', zone %></td>
        <td><%= link_to 'Edit', edit_zone_path(zone) %></td>
        <td><%= link_to 'Destroy', zone, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zone', new_zone_path %>
 -->
<div class="row">
  <div class="col-md-8">
    <form class="form-inline block">
      <div class="input-group mb-2 mr-sm-2" style="width:100%">

        <label class="sr-only" for="search">Search domain names</label>
        <input class="form-control my-1 mr-sm-2" type="search" placeholder="Search websites in my account" aria-label="Search" name="search">
        <button class="btn btn-outline-success my-1 mr-sm-2" type="submit">Search</button>
      </div>
    </form>
  </div>
  <div class="col-md-2">
    <%= link_to "+ Add Site", new_zone_path, class: "btn btn-primary" %>
  </div>
</div>

All zones:

<%- @zones.in_groups_of(2).each do |zones| %>
  <div class="row">
    <%- zones.each do |zone| %>
    <%- if zone %>
      <div class="col">
        <%= link_to zone.name, zone.name %>
      </div>
      <%- end %>
    <%- end %>
  </div>
<%- end %>


<%= @zones.in_groups_of(2) %>

app/views/zones/new.html.erb
<%= render 'form', zone: @zone %>

<%= link_to 'Back', zones_path %>

app/views/zones/show.html.erb
<p>
  DNS Management for:
  <strong><%= @zone.name %></strong>
</p>

<%= form_for [@zone, @dns_record] do |form| %>
  <div class="form-row">
    <div class="form-group col">
      <%= form.label :record_type, "Type" %><br />
      <%= form.select :record_type, DnsRecord.record_types.keys, class: 'form-control' %>
    </div>
    <div class="form-group col">
      <%= form.label :name %><br />
      <%= form.text_field :name, placeholder: "Use @ for root" %>
    </div>
    <div class="form-group col">
      <%= form.label :value %><br />
      <%= form.text_field :value %>
    </div>
    <div class="form-group col">
      <%= form.label :ttl, "TTL" %><br />
      <%= form.select :ttl, [
        ['2 min', 2 * 60],
        ['5 min', 5 * 60],
        ['10m', 10 * 60],
        ['15m', 15 * 60],
        ['30m', 30 * 60],
        ['1h', 1 * 60 * 60],
        ['2h', 2 * 60 * 60],
        ['5h', 5 * 60 * 60],
        ['12h', 12 * 60 * 60],
        ['1d', 24 * 60 * 60],
        ], prompt: "Auto" %>
    </div>
    <div class="form-group row">
      <div class="col-sm-10">
        <button class="btn btn-primary">Add</button>
      </div>
    </div>
  </div>
<%- end %>

<table class="table table-striped">
  <tr>
    <th>Type</th>
    <th>Name</th>
    <th>Content</th>
    <th>TTL</th>
    <th></th>
  </tr>
  <%- @zone.dns_records.filter{|a| a.id.present?}.each do |record|%>
    <tr>
      <td><%= record.record_type %></td>
      <td><%= record.name %></td>
      <td><%= record.value %></td>
      <td><%= distance_of_time_in_words(record.ttl).sub("about ", "") %></td>
      <td><%= link_to "X", [@zone, record], method: :delete, data: {confirm: "Are you sure" } %></td>
    </tr>
  <%- end %>
</table>

<pre>
<%= @zone.dump %>
</pre>
<br />

<%= link_to 'Edit', edit_zone_path(@zone) %> |
<%= link_to 'Back', zones_path %>